# Generated by Django 5.2.4 on 2025-07-18 08:26

import apps.accounts.models
import django.db.models.deletion
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_code', models.CharField(default=apps.accounts.models.generate_activation_code, help_text="A unique code for activating the user's account.", max_length=6, unique=True, verbose_name='Activation Code')),
                ('is_active', models.BooleanField(default=False, help_text="Indicates whether the user's account is active.", verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the activation was created.', verbose_name='Created At')),
                ('expiration_date', models.DateTimeField(default=apps.accounts.models.generate_activation_code_expiration, help_text='The date and time when the activation code expires.', verbose_name='Expiration Date')),
                ('user', models.OneToOneField(help_text='The user associated with this activation.', on_delete=django.db.models.deletion.CASCADE, related_name='activation', to=settings.AUTH_USER_MODEL, verbose_name='User Activation')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='defaults/avatar.png', force_format=None, help_text="User's profile picture, resized to 200x200 pixels.", keep_meta=True, null=True, quality=90, scale=None, size=[200, 200], upload_to='uploads/avatars/', verbose_name='Avatar')),
                ('user', models.OneToOneField(help_text='The user associated with this profile.', on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL, verbose_name='User Profile')),
            ],
        ),
    ]
