# Generated by Django 5.2.4 on 2025-07-20 11:59

import apps.accounts.models
import django.db.models.deletion
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the team, must be unique.', max_length=255, unique=True, verbose_name='Team Name')),
                ('slug', models.SlugField(default=apps.accounts.models.generate_team_slug, help_text='A unique identifier for the team, used in URLs.', max_length=255, unique=True, verbose_name='Team Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the team was created.', verbose_name='Created At')),
                ('logo', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='defaults/team_logo.png', force_format=None, help_text="Team's logo, resized to 200x200 pixels.", keep_meta=True, null=True, quality=90, scale=None, size=[200, 200], upload_to='uploads/team_logos/', verbose_name='Team Logo')),
                ('owner', models.ForeignKey(help_text='The user who owns the team.', on_delete=django.db.models.deletion.CASCADE, related_name='owned_teams', to=settings.AUTH_USER_MODEL, verbose_name='Team Owner')),
                ('plan', models.ForeignKey(help_text='The billing plan associated with the team.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='billing.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', help_text='The role of the user in the team.', max_length=50, verbose_name='Role')),
                ('team', models.ForeignKey(help_text='The team to which the user belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='team_membership', to='accounts.team', verbose_name='Team')),
                ('user', models.ForeignKey(help_text='The user who is a member of the team.', on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'unique_together': {('user', 'team')},
            },
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(help_text='Users who are members of the team.', related_name='teams', through='accounts.TeamMember', to=settings.AUTH_USER_MODEL, verbose_name='Team Members'),
        ),
        migrations.CreateModel(
            name='UserActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_code', models.CharField(default=apps.accounts.models.generate_activation_code, help_text="A unique code for activating the user's account.", max_length=6, unique=True, verbose_name='Activation Code')),
                ('is_active', models.BooleanField(default=False, help_text="Indicates whether the user's account is active.", verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the activation was created.', verbose_name='Created At')),
                ('expiration_date', models.DateTimeField(default=apps.accounts.models.generate_activation_code_expiration, help_text='The date and time when the activation code expires.', verbose_name='Expiration Date')),
                ('user', models.OneToOneField(help_text='The user associated with this activation.', on_delete=django.db.models.deletion.CASCADE, related_name='activation', to=settings.AUTH_USER_MODEL, verbose_name='User Activation')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='defaults/avatar.png', force_format=None, help_text="User's profile picture, resized to 200x200 pixels.", keep_meta=True, null=True, quality=90, scale=None, size=[200, 200], upload_to='uploads/avatars/', verbose_name='Avatar')),
                ('user', models.OneToOneField(help_text='The user associated with this profile.', on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL, verbose_name='User Profile')),
            ],
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='The email address of the user being invited.', max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the invitation was created.', verbose_name='Created At')),
                ('accepted', models.BooleanField(default=False, help_text='Indicates whether the invitation has been accepted.', verbose_name='Accepted')),
                ('invited_by', models.ForeignKey(help_text='The user who sent the invitation.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Invited By')),
                ('team', models.ForeignKey(help_text='The team to which the user is being invited.', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Team Invitation',
                'verbose_name_plural': 'Team Invitations',
                'unique_together': {('email', 'team')},
            },
        ),
    ]
