# Generated by Django 5.2.4 on 2025-07-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(help_text='A unique identifier for the team, used in URLs.', max_length=255, unique=True, verbose_name='Team Slug'),
        ),
    ]
