# Generated by Django 5.2.4 on 2025-07-11 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='plan_expiry_at',
            new_name='plan_expires_at',
        ),
    ]
