# Generated by Django 5.2.4 on 2025-07-13 08:38

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='defaults/avatar.png', force_format=None, help_text="User's profile picture, resized to 200x200 pixels.", keep_meta=True, quality=90, scale=None, size=[200, 200], upload_to='avatars/', verbose_name='Avatar'),
        ),
    ]
