# Generated by Django 5.2.4 on 2025-07-14 04:57

import django.db.models.deletion
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='defaults/avatar.png', force_format=None, help_text="User's profile picture, resized to 200x200 pixels.", keep_meta=True, null=True, quality=90, scale=None, size=[200, 200], upload_to='uploads/avatars/', verbose_name='Avatar')),
                ('user', models.OneToOneField(help_text='The user associated with this profile.', on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL, verbose_name='User Profile')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
