# Generated by Django 5.2.4 on 2025-07-14 06:00

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userprofile_delete_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_code', models.CharField(default=apps.accounts.models.generate_activation_code, help_text="A unique code for activating the user's account.", max_length=6, unique=True, verbose_name='Activation Code')),
                ('is_active', models.BooleanField(default=False, help_text="Indicates whether the user's account is active.", verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the activation was created.', verbose_name='Created At')),
                ('expiration_date', models.DateTimeField(default=apps.accounts.models.generate_activation_code_expiration, help_text='The date and time when the activation code expires.', verbose_name='Expiration Date')),
                ('user', models.OneToOneField(help_text='The user associated with this activation.', on_delete=django.db.models.deletion.CASCADE, related_name='activation', to=settings.AUTH_USER_MODEL, verbose_name='User Activation')),
            ],
        ),
    ]
