services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: .
          target: ./app
          ignore:
            - venv/
            - .git/
            - node_modules/
            - apps/core/static/build.css
        - action: rebuild
          path: requirements.txt

  db:
    image: postgres:16
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
  pgdata:
