# Generated by Django 5.2.4 on 2025-07-20 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the billing plan.', max_length=100, unique=True, verbose_name='Plan Name')),
                ('slug', models.SlugField(help_text='A URL-friendly identifier for the billing plan.', max_length=100, unique=True, verbose_name='Plan Slug')),
                ('price', models.DecimalField(decimal_places=2, help_text='The price of the billing plan in the INR (₹).', max_digits=10, verbose_name='Plan Price')),
                ('description', models.TextField(blank=True, help_text='A description of this plan.', verbose_name='Plan Description')),
                ('is_active', models.BooleanField(default=True, help_text='Is the plan currently visible and available for users to select?', verbose_name='Is Active')),
                ('visible', models.BooleanField(default=True, help_text='Is the plan visible to users?', verbose_name='Visible')),
                ('highlighted', models.BooleanField(default=False, help_text='Whether this plan should be highlighted in the UI.', verbose_name='Highlighted')),
                ('ranking', models.PositiveIntegerField(default=0, help_text='The ranking of the plan for display purposes.', verbose_name='Ranking')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the plan was created.', verbose_name='Created At')),
                ('is_base_plan', models.BooleanField(default=False, help_text='Indicates if this is the base plan that all teams start with.', verbose_name='Is Base Plan')),
            ],
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='A unique key for the feature, used for identification.', max_length=100, verbose_name='Feature Key')),
                ('value', models.CharField(help_text='The value of the feature, which can be a string or JSON.', max_length=255, verbose_name='Feature Value')),
                ('plan', models.ForeignKey(help_text='The billing plan this feature belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='billing.plan', verbose_name='Plan')),
            ],
            options={
                'unique_together': {('plan', 'key')},
            },
        ),
    ]
