# Generated by Django 5.2.4 on 2025-07-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the billing plan.', max_length=100, unique=True, verbose_name='Plan Name')),
                ('slug', models.SlugField(help_text='A URL-friendly identifier for the billing plan.', max_length=100, unique=True, verbose_name='Plan Slug')),
                ('price', models.DecimalField(decimal_places=2, help_text='The price of the billing plan in the smallest currency unit (e.g., cents).', max_digits=10, verbose_name='Plan Price')),
                ('features', models.TextField(blank=True, help_text='A description of the features included in this plan.', verbose_name='Plan Features')),
                ('is_pro', models.BooleanField(default=False, help_text='Is this plan a Pro plan?', verbose_name='Is Pro Plan')),
                ('requires_expiry', models.BooleanField(default=False, help_text='Does this plan require an expiry date?', verbose_name='Requires Expiry Date')),
                ('pageview_limit', models.PositiveIntegerField(default=0, help_text='The maximum number of pageviews allowed per month. 0 means unlimited.', verbose_name='Pageview Limit')),
                ('script_bagde', models.BooleanField(default=False, help_text='Whether the plan includes a script badge.', verbose_name='Script Badge')),
                ('is_active', models.BooleanField(default=True, help_text='Is the plan currently visible and available for users to select?', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the plan was created.', verbose_name='Created At')),
            ],
        ),
    ]
