# Generated by Django 5.2.4 on 2025-07-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='ranking',
            field=models.PositiveIntegerField(default=0, help_text='The ranking of the plan for display purposes.', verbose_name='Ranking'),
        ),
    ]
