# Generated by Django 5.2.4 on 2025-07-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='The price of the billing plan in the INR (₹).', max_digits=10, null=True, verbose_name='Plan Price'),
        ),
    ]
