# Generated by Django 5.2.4 on 2025-07-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_plan_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='ranking',
            field=models.PositiveIntegerField(default=0, help_text='The ranking of the plan for display purposes.', unique=True, verbose_name='Ranking'),
        ),
    ]
