# Generated by Django 5.2.4 on 2025-07-20 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_team_slug'),
        ('billing', '0002_alter_plan_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RedeemCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The unique code that can be redeemed for a billing plan.', max_length=50, unique=True, verbose_name='Redeem Code')),
                ('description', models.TextField(blank=True, help_text='A description of what the redeem code offers.', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the redeem code is currently active.', verbose_name='Is Active')),
                ('usage_limit', models.PositiveIntegerField(default=1, help_text='The maximum number of times this redeem code can be used.', verbose_name='Usage Limit')),
                ('used_count', models.PositiveIntegerField(default=0, help_text='The number of times this redeem code has been used.', verbose_name='Used Count')),
                ('valid_from', models.DateTimeField(blank=True, help_text='The date and time from which the redeem code is valid.', null=True, verbose_name='Valid From')),
                ('valid_until', models.DateTimeField(blank=True, help_text='The date and time until which the redeem code is valid.', null=True, verbose_name='Valid Until')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the redeem code was created.', verbose_name='Created At')),
                ('plan', models.ForeignKey(help_text='The billing plan that this redeem code applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='redeem_codes', to='billing.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Redeem Code',
                'verbose_name_plural': 'Redeem Codes',
                'ordering': ['-created_at'],
                'unique_together': {('code', 'plan')},
            },
        ),
        migrations.CreateModel(
            name='CodeRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the code was redeemed.', verbose_name='Redeemed At')),
                ('team', models.ForeignKey(help_text='The team for which the code was redeemed.', on_delete=django.db.models.deletion.CASCADE, related_name='code_redemptions', to='accounts.team', verbose_name='Team')),
                ('user', models.ForeignKey(help_text='The user who redeemed the code.', on_delete=django.db.models.deletion.CASCADE, related_name='code_redemptions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('redeem_code', models.ForeignKey(help_text='The redeem code that was redeemed.', on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='billing.redeemcode', verbose_name='Redeem Code')),
            ],
            options={
                'verbose_name': 'Code Redemption',
                'verbose_name_plural': 'Code Redemptions',
                'ordering': ['-redeemed_at'],
                'unique_together': {('redeem_code', 'user', 'team')},
            },
        ),
    ]
