# Generated by Django 5.2.4 on 2025-07-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_plan_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='highlighted',
            field=models.BooleanField(default=False, help_text='Whether this plan should be highlighted in the UI.', verbose_name='Highlighted'),
        ),
    ]
