# Generated by Django 5.2.4 on 2025-07-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_plan_highlighted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='The price of the billing plan in the INR (₹).', max_digits=10, verbose_name='Plan Price'),
        ),
    ]
