# Generated by Django 5.2.4 on 2025-07-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_plan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='visible',
            field=models.BooleanField(default=True, help_text='Is the plan visible to users?', verbose_name='Visible'),
        ),
    ]
