# Generated by Django 5.2.4 on 2025-07-13 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_plan_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='features',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='is_pro',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='pageview_limit',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='requires_expiry',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='script_bagde',
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, help_text='A description of this plan.', verbose_name='Plan Description'),
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='A unique key for the feature, used for identification.', max_length=100, verbose_name='Feature Key')),
                ('value', models.CharField(help_text='The value of the feature, which can be a string or JSON.', max_length=255, verbose_name='Feature Value')),
                ('plan', models.ForeignKey(help_text='The billing plan this feature belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='billing.plan', verbose_name='Plan')),
            ],
            options={
                'unique_together': {('plan', 'key')},
            },
        ),
    ]
