# Generated by Django 5.2.4 on 2025-07-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_remove_plan_features_remove_plan_is_pro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_base_plan',
            field=models.BooleanField(default=False, help_text='Indicates if this is the base plan that all teams start with.', verbose_name='Is Base Plan'),
        ),
    ]
