# Generated by Django 5.2.4 on 2025-07-21 16:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the event.', primary_key=True, serialize=False, verbose_name='Event ID')),
                ('type', models.CharField(help_text='Type of the event.', max_length=100, verbose_name='Event Type')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the event was created.', verbose_name='Timestamp')),
                ('data', models.JSONField(blank=True, help_text='Additional data related to the event.', null=True, verbose_name='Event Data')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Detailed message about the event log.', verbose_name='Log Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the log entry was created.', verbose_name='Created At')),
                ('event', models.ForeignKey(help_text='The event associated with this log entry.', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='hooks.event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Event Log',
                'verbose_name_plural': 'Event Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='The URL to which the webhook will send event notifications.', verbose_name='Webhook URL')),
                ('event_type', models.CharField(help_text='Type of event this webhook is subscribed to.', max_length=100, verbose_name='Event Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the webhook was created.', verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhooks',
                'unique_together': {('url', 'event_type')},
            },
        ),
        migrations.CreateModel(
            name='EventSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text='Type of event the user is subscribed to.', max_length=100, verbose_name='Event Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the subscription was created.', verbose_name='Created At')),
                ('user', models.ForeignKey(help_text='The user who subscribed to the event.', on_delete=django.db.models.deletion.CASCADE, related_name='event_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Event Subscription',
                'verbose_name_plural': 'Event Subscriptions',
                'unique_together': {('user', 'event_type')},
            },
        ),
    ]
