# Generated by Django 5.2.4 on 2025-07-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='secret',
            field=models.CharField(default=1, help_text='The secret key used to sign the webhook payload.', max_length=100, verbose_name='Secret'),
            preserve_default=False,
        ),
    ]
