# Generated by Django 5.2.4 on 2025-07-21 17:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hooks', '0002_webhook_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('form.submitted', 'Form Submitted'), ('team.plan_changed', 'Team Plan Changed'), ('form.deleted', 'Form Deleted'), ('visitor.session', 'Visitor Session')], max_length=64)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('team_id', models.CharField(max_length=64)),
                ('site_id', models.CharField(blank=True, max_length=64, null=True)),
                ('data', models.JSONField()),
                ('delivered', models.BooleanField(default=False)),
                ('delivery_attempts', models.PositiveIntegerField(default=0)),
                ('last_delivery_status', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='event',
        ),
        migrations.AlterUniqueTogether(
            name='eventsubscription',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='eventsubscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='Webhook',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventLog',
        ),
        migrations.DeleteModel(
            name='EventSubscription',
        ),
    ]
