# Generated by Django 5.2.4 on 2025-07-22 08:59

import apps.hooks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hooks', '0003_webhookevent_remove_eventlog_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookevent',
            name='id',
            field=models.CharField(default=apps.hooks.models.generate_event_id, editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
