# Generated by Django 5.2.4 on 2025-07-11 09:28

import apps.sites.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_site_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='verification_token',
            field=models.CharField(default=apps.sites.models.generate_verification_token, help_text='A unique token used to verify ownership of the site. Place this in a file at the root of your domain as ~/.well-known/pingfox-verification.txt. ', max_length=256, unique=True, verbose_name='Verification Token'),
        ),
    ]
