# Generated by Django 5.2.4 on 2025-07-12 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_alter_site_verification_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='The URL of the page that was viewed.', verbose_name='URL')),
                ('referrer', models.URLField(blank=True, help_text='The URL of the page that referred the user to this page.', verbose_name='Referrer')),
                ('user_agent', models.TextField(help_text='The user agent string of the browser making the request.', verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the page view was recorded.', verbose_name='Created At')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pageviews', to='sites.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
                'ordering': ['-created_at'],
            },
        ),
    ]
