# Generated by Django 5.2.4 on 2025-07-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_pageview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageView',
        ),
    ]
