# Generated by Django 5.2.4 on 2025-07-16 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_delete_pageview'),
        ('teams', '0006_team_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='user',
        ),
        migrations.AddField(
            model_name='site',
            name='onwer',
            field=models.ForeignKey(default=1, help_text='The user who made this site.', on_delete=django.db.models.deletion.CASCADE, related_name='sites', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='team',
            field=models.ForeignKey(default=1, help_text='The team that owns this site.', on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='teams.team', verbose_name='Team'),
            preserve_default=False,
        ),
    ]
