# Generated by Django 5.2.4 on 2025-07-16 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_remove_site_user_site_onwer_site_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='onwer',
            new_name='owner',
        ),
    ]
