# Generated by Django 5.2.4 on 2025-07-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_rename_onwer_site_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='url',
            field=models.URLField(default='', help_text="The full URL for this site (e.g. 'https://example.com').", max_length=255, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
