# Generated by Django 5.2.4 on 2025-07-18 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0019_form_site_id'),
        ('sites', '0008_site_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='form',
            field=models.ForeignKey(blank=True, help_text='The form associated with this site, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='forms.form', verbose_name='Form'),
        ),
    ]
