# Generated by Django 5.2.4 on 2025-07-13 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the form.', max_length=255, verbose_name='Form Name')),
                ('slug', models.SlugField(help_text='A unique identifier for the form, used in URLs.', max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='A brief description of the form.', null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the form was created.', verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the form is currently active.', verbose_name='Is Active')),
                ('authentication_required', models.BooleanField(default=False, help_text='Indicates whether users must be authenticated to submit this form.', verbose_name='Authentication Required')),
                ('auth_key', models.CharField(default='azOCDlJU59I0WfyclVA58YF0ZONm0GJZlEm5UNwckbgk-xmwNaTAzA', help_text='A unique key required for authenticated form submissions.', max_length=40, unique=True, verbose_name='Authentication Key')),
                ('owner', models.ForeignKey(help_text='The user who owns this form.', on_delete=django.db.models.deletion.CASCADE, related_name='forms', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Form',
                'verbose_name_plural': 'Forms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='The label for the form field.', max_length=255, verbose_name='Field Label')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('number', 'Number'), ('date', 'Date'), ('checkbox', 'Checkbox'), ('select', 'Select'), ('textarea', 'Textarea')], help_text='The type of the form field.', max_length=50, verbose_name='Field Type')),
                ('name', models.SlugField(help_text='A unique identifier for the field, used in form submissions.', max_length=255, verbose_name='Field Name')),
                ('placeholder', models.CharField(blank=True, help_text='Placeholder text for the field.', max_length=255, null=True, verbose_name='Placeholder')),
                ('required', models.BooleanField(default=False, help_text='Indicates whether this field is required.', verbose_name='Is Required')),
                ('choices', models.TextField(blank=True, help_text='Comma-separated list of choices (for select only).', null=True, verbose_name='Choices')),
                ('order', models.PositiveIntegerField(default=0, help_text='The order of the field in the form.', verbose_name='Order')),
                ('validation_regex', models.CharField(blank=True, help_text='Regular expression for validating the field input.', max_length=255, null=True, verbose_name='Validation Regex')),
                ('form', models.ForeignKey(help_text='The form to which this field belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms.form', verbose_name='Form')),
            ],
            options={
                'verbose_name': 'Form Field',
                'verbose_name_plural': 'Form Fields',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the form was submitted.', verbose_name='Submitted At')),
                ('data', models.JSONField(help_text='The data submitted in the form.', verbose_name='Submission Data')),
                ('form', models.ForeignKey(help_text='The form to which this submission belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms.form', verbose_name='Form')),
            ],
            options={
                'verbose_name': 'Form Submission',
                'verbose_name_plural': 'Form Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['slug'], name='forms_form_slug_64e4aa_idx'),
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['owner'], name='forms_form_owner_i_009fd7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='form',
            unique_together={('owner', 'slug')},
        ),
    ]
