# Generated by Django 5.2.4 on 2025-07-13 12:20

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='auth_key',
            field=models.CharField(default='FSBLaZWz_qPrtoDbGMZ2Os5Po7E-HQ83fNbYAys5_Skru4ZTdz5hFg', help_text='A unique key required for authenticated form submissions.', max_length=40, unique=True, verbose_name='Authentication Key'),
        ),
        migrations.CreateModel(
            name='FormStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(default='#ffffff', help_text='The background color of the form in hex format.', max_length=7, verbose_name='Background Color')),
                ('text_color', models.CharField(default='#000000', help_text='The text color of the form in hex format.', max_length=7, verbose_name='Text Color')),
                ('font_family', models.CharField(default='Arial, sans-serif', help_text='The font family used in the form.', max_length=100, verbose_name='Font Family')),
                ('logo', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, help_text='The logo image for the form.', keep_meta=True, null=True, quality=90, scale=None, size=[300, 100], upload_to='form_logos/', verbose_name='Logo')),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS styles for the form.', null=True, verbose_name='Custom CSS')),
                ('form', models.OneToOneField(help_text='The form to which this style belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='style', to='forms.form', verbose_name='Form')),
            ],
            options={
                'verbose_name': 'Form Style',
                'verbose_name_plural': 'Form Styles',
            },
        ),
    ]
