# Generated by Django 5.2.4 on 2025-07-20 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='site_id',
        ),
    ]
