# Generated by Django 5.2.4 on 2025-07-13 12:23

import apps.forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_form_auth_key_formstyle'),
    ]

    operations = [
        migrations.AddField(
            model_name='formstyle',
            name='accent_color',
            field=models.CharField(default='#007bff', help_text='The accent color used in the form, such as for buttons.', max_length=7, verbose_name='Accent Color'),
        ),
        migrations.AlterField(
            model_name='form',
            name='auth_key',
            field=models.CharField(default=apps.forms.models.generate_auth_key, help_text='A unique key required for authenticated form submissions.', max_length=40, unique=True, verbose_name='Authentication Key'),
        ),
    ]
