# Generated by Django 5.2.4 on 2025-07-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_remove_form_site_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='URL to send webhook notifications for form submissions.', null=True, verbose_name='Webhook URL'),
        ),
    ]
