# Generated by Django 5.2.4 on 2025-07-13 12:27

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_formstyle_accent_color_alter_form_auth_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formstyle',
            name='accent_color',
            field=colorfield.fields.ColorField(default='#007bff', help_text='The accent color used for buttons and highlights in the form.', image_field=None, max_length=25, samples=None, verbose_name='Accent Color'),
        ),
        migrations.AlterField(
            model_name='formstyle',
            name='background_color',
            field=colorfield.fields.ColorField(default='#ffffff', help_text='The background color of the form in hex format.', image_field=None, max_length=25, samples=None, verbose_name='Background Color'),
        ),
        migrations.AlterField(
            model_name='formstyle',
            name='font_family',
            field=models.CharField(choices=[('system', 'System Default'), ('inter', 'Inter'), ('dyslexic', 'OpenDyslexic'), ('serif', 'Serif'), ('mono', 'Monospace'), ('sans-serif', 'Sans-Serif')], default='Arial, sans-serif', help_text='The font family used in the form.', max_length=100, verbose_name='Font Family'),
        ),
        migrations.AlterField(
            model_name='formstyle',
            name='text_color',
            field=colorfield.fields.ColorField(default='#000000', help_text='The text color used in the form, such as for labels and instructions.', image_field=None, max_length=25, samples=None, verbose_name='Text Color'),
        ),
    ]
