# Generated by Django 5.2.4 on 2025-07-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_form_webhook_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='webhook_secret',
            field=models.CharField(blank=True, help_text='Secret key used to sign webhook payloads.', max_length=64, null=True, verbose_name='Webhook Secret'),
        ),
    ]
