# Generated by Django 5.2.4 on 2025-07-13 12:40

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_alter_formstyle_accent_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formstyle',
            name='accent_color',
            field=colorfield.fields.ColorField(default='#f97316', help_text='The accent color used for buttons and highlights in the form.', image_field=None, max_length=25, samples=None, verbose_name='Accent Color'),
        ),
    ]
