# Generated by Django 5.2.4 on 2025-07-14 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_alter_formstyle_accent_color'),
        ('teams', '0002_team_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='team',
            field=models.ForeignKey(default=1, help_text='The team to which this form belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='teams.team', verbose_name='Team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form',
            name='owner',
            field=models.ForeignKey(help_text='The user who owns the form.', on_delete=django.db.models.deletion.CASCADE, related_name='forms', to=settings.AUTH_USER_MODEL, verbose_name='Form Owner'),
        ),
    ]
