# Generated by Django 5.2.4 on 2025-07-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_form_team_alter_form_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='choices',
            field=models.CharField(blank=True, help_text='Comma-separated list of choices (for select only).', max_length=255, null=True, verbose_name='Choices'),
        ),
    ]
