# Generated by Django 5.2.4 on 2025-07-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_alter_formfield_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('number', 'Number'), ('date', 'Date'), ('checkbox', 'Checkbox'), ('select', 'Select'), ('radio', 'Radio'), ('textarea', 'Textarea')], help_text='The type of the form field.', max_length=50, verbose_name='Field Type'),
        ),
    ]
