# Generated by Django 5.2.4 on 2025-07-15 09:14

import apps.forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_alter_formfield_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='slug',
            field=models.SlugField(default=apps.forms.models.generate_slug, help_text='A unique identifier for the form, used in URLs.', max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
