# Generated by Django 5.2.4 on 2025-07-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_alter_form_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Indicates whether the form is locked for editing.', verbose_name='Is Locked'),
        ),
    ]
