# Generated by Django 5.2.4 on 2025-07-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_form_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='help_text',
            field=models.CharField(blank=True, help_text='Additional information or instructions for the field.', max_length=255, null=True, verbose_name='Help Text'),
        ),
    ]
