# Generated by Django 5.2.4 on 2025-07-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_formfield_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='default_value',
            field=models.TextField(blank=True, help_text='The default value for the field, if applicable.', null=True, verbose_name='Default Value'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='disabled',
            field=models.BooleanField(default=False, help_text='Indicates whether this field is disabled.', verbose_name='Is Disabled'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Indicates whether this field is hidden from the user.', verbose_name='Is Hidden'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='readonly',
            field=models.BooleanField(default=False, help_text='Indicates whether this field is readonly.', verbose_name='Is Readonly'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='choices',
            field=models.CharField(blank=True, help_text='Comma-separated list of choices (for select only).', max_length=2048, null=True, verbose_name='Choices'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='help_text',
            field=models.CharField(blank=True, help_text='Additional information or instructions for the field.', max_length=1024, null=True, verbose_name='Help Text'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='label',
            field=models.CharField(help_text='The label for the form field.', max_length=1024, verbose_name='Field Label'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='name',
            field=models.SlugField(help_text='A unique identifier for the field, used in form submissions.', max_length=1024, verbose_name='Field Name'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='placeholder',
            field=models.CharField(blank=True, help_text='Placeholder text for the field.', max_length=1024, null=True, verbose_name='Placeholder'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='validation_regex',
            field=models.CharField(blank=True, help_text='Regular expression for validating the field input.', max_length=1024, null=True, verbose_name='Validation Regex'),
        ),
    ]
