# Generated by Django 5.2.4 on 2025-07-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_formfield_default_value_formfield_disabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='allow_anonymous_submissions',
            field=models.BooleanField(default=False, help_text='Indicates whether the form can be submitted by users who are not authenticated.', verbose_name='Allow Anonymous Submissions'),
        ),
        migrations.AddField(
            model_name='form',
            name='allow_multiple_submissions',
            field=models.BooleanField(default=False, help_text='Indicates whether users can submit this form multiple times.', verbose_name='Allow Multiple Submissions'),
        ),
        migrations.AddField(
            model_name='form',
            name='redirect_url',
            field=models.URLField(blank=True, help_text='URL to redirect users after form submission.', null=True, verbose_name='Redirect URL'),
        ),
    ]
