# Generated by Django 5.2.4 on 2025-07-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_visitorsession_and_more'),
        ('forms', '0013_form_allow_anonymous_submissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='visitors',
            field=models.ManyToManyField(blank=True, help_text='Visitors who have interacted with this form.', related_name='forms', to='analytics.visitorsession', verbose_name='Visitors'),
        ),
    ]
