# Generated by Django 5.2.4 on 2025-07-16 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_form_visitors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='allow_anonymous_submissions',
        ),
    ]
