# Generated by Django 5.2.4 on 2025-07-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0015_remove_form_allow_anonymous_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='button_text',
            field=models.CharField(default='Submit', help_text='The text displayed on the form submission button.', max_length=255, verbose_name='Button Text'),
        ),
        migrations.AlterField(
            model_name='form',
            name='allow_multiple_submissions',
            field=models.BooleanField(default=True, help_text='Indicates whether users can submit this form multiple times.', verbose_name='Allow Multiple Submissions'),
        ),
    ]
