# Generated by Django 5.2.4 on 2025-07-17 09:41

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_form_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formstyle',
            name='button_color',
            field=colorfield.fields.ColorField(default='#f97316', help_text='The color of the form submission button.', image_field=None, max_length=25, samples=None, verbose_name='Button Color'),
        ),
        migrations.AddField(
            model_name='formstyle',
            name='button_text_color',
            field=colorfield.fields.ColorField(default='#ffffff', help_text='The text color of the form submission button.', image_field=None, max_length=25, samples=None, verbose_name='Button Text Color'),
        ),
    ]
