# Generated by Django 5.2.4 on 2025-07-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0017_formstyle_button_color_formstyle_button_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='allow_analytics',
            field=models.BooleanField(default=True, help_text='Indicates whether analytics are enabled for this form.', verbose_name='Allow Analytics'),
        ),
    ]
