# Generated by Django 5.2.4 on 2025-07-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0018_form_allow_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='site_id',
            field=models.CharField(blank=True, help_text='The ID of the site where this form is hosted, entered if analytics are enabled.', max_length=255, null=True, verbose_name='Site ID'),
        ),
    ]
