# Generated by Django 5.2.4 on 2025-07-14 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the team, must be unique.', max_length=255, unique=True, verbose_name='Team Name')),
                ('slug', models.SlugField(help_text='A unique identifier for the team, used in URLs.', max_length=255, unique=True, verbose_name='Team Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the team was created.', verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', help_text='The role of the user in the team.', max_length=50, verbose_name='Role')),
                ('team', models.ForeignKey(help_text='The team to which the user belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.team', verbose_name='Team')),
                ('user', models.ForeignKey(help_text='The user who is a member of the team.', on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'unique_together': {('user', 'team')},
            },
        ),
    ]
