# Generated by Django 5.2.4 on 2025-07-14 08:24

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='defaults/team_logo.png', force_format=None, help_text="Team's logo, resized to 200x200 pixels.", keep_meta=True, null=True, quality=90, scale=None, size=[200, 200], upload_to='uploads/team_logos/', verbose_name='Team Logo'),
        ),
    ]
