# Generated by Django 5.2.4 on 2025-07-14 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_remove_teammember_logo_team_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(help_text='Users who are members of the team.', related_name='teams', through='teams.TeamMember', to=settings.AUTH_USER_MODEL, verbose_name='Team Members'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(help_text='The team to which the user belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='team_membership', to='teams.team', verbose_name='Team'),
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='The email address of the user being invited.', max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the invitation was created.', verbose_name='Created At')),
                ('accepted', models.BooleanField(default=False, help_text='Indicates whether the invitation has been accepted.', verbose_name='Accepted')),
                ('invited_by', models.ForeignKey(help_text='The user who sent the invitation.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Invited By')),
                ('team', models.ForeignKey(help_text='The team to which the user is being invited.', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Team Invitation',
                'verbose_name_plural': 'Team Invitations',
                'unique_together': {('email', 'team')},
            },
        ),
    ]
