# Generated by Django 5.2.4 on 2025-07-14 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_remove_plan_features_remove_plan_is_pro_and_more'),
        ('teams', '0005_team_members_alter_teammember_team_teaminvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='plan',
            field=models.ForeignKey(help_text='The billing plan associated with the team.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='billing.plan', verbose_name='Plan'),
        ),
    ]
