# Generated by Django 5.2.4 on 2025-07-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='The URL of the page that was viewed.', verbose_name='URL')),
                ('referrer', models.URLField(blank=True, help_text='The URL of the page that referred the visitor to this page.', null=True, verbose_name='Referrer')),
                ('screen_width', models.PositiveIntegerField(blank=True, help_text="The width of the visitor's screen in pixels.", null=True, verbose_name='Screen Width')),
                ('screen_height', models.PositiveIntegerField(blank=True, help_text="The height of the visitor's screen in pixels.", null=True, verbose_name='Screen Height')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the page view occurred.', verbose_name='Timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf_id', models.CharField(help_text='Unique identifier for the visitor, generated at the client side.', max_length=255, unique=True, verbose_name='PF ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the visitor session was created.', verbose_name='Created At')),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='Timestamp when the visitor was last seen.', verbose_name='Last Seen')),
                ('user_agent', models.CharField(help_text="User agent string of the visitor's browser.", max_length=512, verbose_name='User Agent')),
            ],
        ),
    ]
