# Generated by Django 5.2.4 on 2025-07-12 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0005_delete_pageview'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(max_length=64)),
                ('url', models.URLField()),
                ('title', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('user_agent', models.TextField()),
                ('screen_width', models.PositiveIntegerField()),
                ('screen_height', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pageviews', to='sites.site')),
            ],
            options={
                'indexes': [models.Index(fields=['site', 'timestamp'], name='analytics_p_site_id_e1d326_idx')],
            },
        ),
    ]
