# Generated by Django 5.2.4 on 2025-07-12 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('sites', '0005_delete_pageview'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf_id', models.CharField(help_text='Unique identifier for the visitor, generated at the client side.', max_length=255, unique=True, verbose_name='PF ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the visitor session was created.', verbose_name='Created At')),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='Timestamp when the visitor was last seen.', verbose_name='Last Seen')),
                ('user_agent', models.CharField(help_text="User agent string of the visitor's browser.", max_length=512, verbose_name='User Agent')),
            ],
        ),
        migrations.RemoveIndex(
            model_name='pageview',
            name='analytics_p_site_id_e1d326_idx',
        ),
        migrations.RemoveField(
            model_name='pageview',
            name='title',
        ),
        migrations.RemoveField(
            model_name='pageview',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='pageview',
            name='visitor_id',
        ),
        migrations.AlterField(
            model_name='pageview',
            name='referrer',
            field=models.URLField(blank=True, default=1, help_text='The URL of the page that referred the visitor to this page.', verbose_name='Referrer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pageview',
            name='screen_height',
            field=models.PositiveIntegerField(blank=True, help_text="The height of the visitor's screen in pixels.", null=True, verbose_name='Screen Height'),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='screen_width',
            field=models.PositiveIntegerField(blank=True, help_text="The width of the visitor's screen in pixels.", null=True, verbose_name='Screen Width'),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='site',
            field=models.ForeignKey(help_text='The site where the page view occurred.', on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='sites.site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='The timestamp when the page view occurred.', verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='url',
            field=models.URLField(help_text='The URL of the page that was viewed.', verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='pageview',
            name='visitor',
            field=models.ForeignKey(default=1, help_text='The visitor session associated with this page view.', on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='analytics.visitorsession', verbose_name='Visitor'),
            preserve_default=False,
        ),
    ]
