# Generated by Django 5.2.4 on 2025-07-18 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='site',
            field=models.ForeignKey(help_text='The site where the page view occurred.', on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='sites.site', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='pageview',
            name='visitor',
            field=models.ForeignKey(help_text='The visitor session associated with this page view.', on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='analytics.visitorsession', verbose_name='Visitor'),
        ),
    ]
