# Generated by Django 5.2.4 on 2025-07-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_visitorsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='referrer',
            field=models.URLField(blank=True, help_text='The URL of the page that referred the visitor to this page.', null=True, verbose_name='Referrer'),
        ),
    ]
