# Generated by Django 5.2.4 on 2025-07-21 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_site_form'),
        ('forms', '0002_remove_form_site_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='form',
            field=models.OneToOneField(blank=True, help_text='The form associated with this site, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site', to='forms.form', verbose_name='Form'),
        ),
    ]
