# Generated by Django 5.2.4 on 2025-07-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_site_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='domain',
            field=models.CharField(blank=True, help_text="The domain name for this site (e.g. 'example.com' - no protocol).", max_length=255, null=True, verbose_name='Domain'),
        ),
    ]
